//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cities.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CitiesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitiesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cities.Resources.CitiesResource", typeof(CitiesResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva York (en inglés: New York City) es la ciudad más poblada del estado homónimo y de los Estados Unidos de América, y la tercera mayor concentración urbana del continente americano, después de Sao Paulo (Brasil) y la Ciudad de México. La ciudad de Nueva York está entre las aglomeraciones urbanas más grandes y más pobladas del mundo.\n\nDesde finales del siglo XIX es uno de los principales centros de comercio y finanzas del mundo. Nueva York está considerada como ciudad global, dadas sus influencias a niv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NuevaYorkDetalle {
            get {
                return ResourceManager.GetString("NuevaYorkDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to París es la capital de Francia y su ciudad más poblada. Capital de la región de Isla de Francia (o &quot;Región Parisina&quot;), es constituida en la única comuna unidepartamental del país. Está situada a ambos márgenes de un largo meandro del río Sena, en el centro de la Cuenca parisina, entre la confluencia del río Marne y el Sena, aguas arriba, y el Oise y el Sena, aguas abajo.\n\nLa ciudad de París, dentro de sus estrechos límites administrativos, tiene una población de 2 273 305 habitantes en 2015. Sin embargo,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParisDetalle {
            get {
                return ResourceManager.GetString("ParisDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roma es una ciudad y capital italiana, de 2 872 082 habitantes, capital de la Ciudad metropolitana de Roma Capital, de la región del Lacio y de Italia. Es el municipio más poblado de Italia y es la cuarta ciudad más poblada de la Unión Europea. Por antonomasia se la conoce como la Ciudad Eterna, l&apos;Urbe (‘la Ciudad’) o Città Eterna.\n\nEn el transcurso de su historia, que abarca tres milenios, llegó a extender sus dominios sobre toda la cuenca del Mediterráneo y gran parte de Europa. Como capital del Imperio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RomaDetalle {
            get {
                return ResourceManager.GetString("RomaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Francisco, de forma oficial la Ciudad y Condado de San Francisco (en inglés: City and County of San Francisco), es una ciudad que ocupa la cuarta posición de ciudad más poblada del estado de California y la 13.ª de Estados Unidos, con una población de aproximadamente 837 442 habitantes en 2013. Es la única ciudad-condado consolidada de California, y al abarcar una superficie territorial de 121 km² cuenta con la segunda densidad de población más alta del país entre las ciudades que superan los 200 000 ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SanFranciscoDetalle {
            get {
                return ResourceManager.GetString("SanFranciscoDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seattle es la ciudad más grande del estado de Washington, en el noroeste de los Estados Unidos de América. El área metropolitana de la ciudad comprende Seattle-Tacoma-Bellevue, es la 15.ª más poblada del país y la mayor del Noroeste del Pacífico. La ciudad está situada entre el lago Washington y la bahía conocida como Puget Sound, junto al océano Pacífico. Se encuentra 155 kilómetros al sur de la frontera entre Estados Unidos y Canadá. Importante centro cultural, educativo y económico de la región, Seattle  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeattleDetalle {
            get {
                return ResourceManager.GetString("SeattleDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevilla es un municipio y una ciudad de España, capital de la provincia homónima y de la comunidad autónoma de Andalucía. Cuenta con 693 878 habitantes en 2015, por lo que es la ciudad más poblada de Andalucía, la cuarta de España después de Madrid, Barcelona y Valencia y la 32.ª de la Unión Europea. El municipio tiene una extensión de 140,8 km². El área metropolitana de Sevilla está compuesta por 46 municipios, incluye a una población de 1 533 230 habitantes (INE, 2014), y ocupa una superficie de 4900 km². [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SevillaDetalle {
            get {
                return ResourceManager.GetString("SevillaDetalle", resourceCulture);
            }
        }
    }
}
